language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev
env:
  - NGINX_VERSION=nginx-1.4.7
  - NGINX_VERSION=nginx-1.6.3
  - NGINX_VERSION=nginx-1.8.0
  - NGINX_VERSION=nginx-1.9.1
script:
  - echo "NGINX_SRC_VER=${NGINX_VERSION}" > nginx_version
  - sh test.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "aGWGYK++jT3o4ENZ4NzkyCHBn1f8eyqXEa7dEph+088qQlnnieqDn3xzlmBA1hiqouZ6ioTICSfYUaXk6h4zte1SX0nR2rO/XJYhseTqaiqgx+1cqw9aWEkwsAYu0oDuND5pMAa2so3zn38UuHLKvOMNEhi/xRXMFx3Bl5P8Pxk="


